### ISSUE TITLE
Recomendacion fullscreen

### ISSUE THREAD

**Issue by mysery** [lucianoutn/NatusVincere#2]
Tener en cuenta que el entregable es solo la carpeta del grupo.
vi que crearon un bat para ejecutar el proyecto en fullscreen, eso luego no podrán entregarlo.
Luego charlamos una forma de solucionar esto, el tp de fútbol del cuatrimestre pasado hizo un "hack" para solventar esto. verifiquen si lo pueden resolver ustedes caso contrario lo vemos.

**Comment by lucianoutn** [comment]
de hecho no pudimos entregarlo con ese .bat. Por culpa de ese .bat se retraso esos 6 minutos nuestra  entrega... xq el gmail lo rebotaba por haber un .bat adentro del rar adjunto.
El objetivo de ese bat era ver el juego en fullscreen para chequear que las posiciones del Hud y demas cosas las estuviésemos usando de forma relativa a la resolución de pantalla y que se vea bien en distintos aspect ratios. (recuerdo que dijeron que había que exponerlo en un proyector).
Cuál seria concretamente la restricción? no se puden usar archivos bash o no se pueden colocar por sobre el nivel de la carpeta "MiGrupo"?

**Comment by mysery** [comment]
La restricción esta en que todo lo que entregan va en la carpeta del Grupo.
Yo al principio les pedí el proyecto pero era porque solo tenia el de
ustedes. Luego las correcciones son con todos los tps entonces empieza a
haber conflictos.
Saludos

**Comment by lucianoutn** [comment]
hecho
